In [1]:
import numpy as np

In [11]:
a=np.array([1,2])
b=np.array([5,6])

In [9]:
z = np.log(a) 
print(z)

[0.         0.69314718 1.09861229 1.38629436]


In [6]:
z = np.sqrt(a)
print(z)

[1.         1.41421356 1.73205081 2.        ]


In [12]:
z = np.dot(a,b)
z = a.dot(b)
print(z)

17


In [16]:
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [19]:
z=np.zeros((2,2))
print(z)

[[0. 0.]
 [0. 0.]]


In [20]:
z=np.ones((5,5))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
z=np.random.random((3,3))
print(z)

[[0.83416913 0.96208942 0.15766804]
 [0.05440135 0.76071274 0.89130507]
 [0.05560215 0.87748245 0.63260195]]


In [26]:
z=np.random.randn(2,2)
print(z)
print(z.mean())
print(z.var())

[[1.27214191 1.87183903]
 [1.01131471 0.09158046]]
1.0617190262746807
0.4110704116748145


In [27]:
p = np.array([[1,2,3],[2,2,1],[6,7,9]])
q = np.array([[4,5],[6,7],[6,8]])

In [28]:
print(p.dot(q))

[[ 34  43]
 [ 26  32]
 [120 151]]


In [30]:
#inverse
z=np.linalg.inv(p)

In [31]:
z.dot(p)

array([[ 1.00000000e+00,  3.33066907e-16,  1.11022302e-16],
       [ 2.22044605e-16,  1.00000000e+00,  1.22124533e-15],
       [-1.11022302e-16, -5.55111512e-17,  1.00000000e+00]])

In [33]:
#determinent
z=np.linalg.det(p)
print(z)

-6.999999999999999


In [36]:
#diagonal matrix
d=np.diag([1,2,3,4])
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [38]:
#trace of  matrix
z=np.trace(d)
print(z)

10
